name: "Run pre-build step"
description: "This action accepts matrices for the jobs that are used in the agent-build workflow and excludes job that are must not be executed in mon-master runs."

inputs:
  step_runner_fqdn:
    description: ""

  cache_key:
    description: ""

  python_version:
    description: ""

  aws_private_key_name:
    description: ""
  aws_region:
    description: ""
  aws_security_group:
    description: ""
  aws_prefix_list_id:
    description: ""
  aws_objects_name_prefix:
    description: ""

  aws_private_key:
    description: ""
  aws_access_key:
    description: ""
  aws_secret_key:
    description: ""


runs:
  using: "composite"
  steps:
    - name: Prepare dev requirements.
      uses: ./.github/actions/prepare_python_with_dev_requirements
      with:
        python_version: ${{ inputs.python_version }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2.0.0
      with:
        driver-opts: network=host

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2
      with:
        image: tonistiigi/binfmt:qemu-v6.2.0
        platforms: all



    - name: Prepare SSH
      id: prepare-ssh
      shell: bash
      run: |
        echo '${{ inputs.aws_private_key }}' > /tmp/private_key.pem
        chmod 600 /tmp/private_key.pem
        eval `ssh-agent -s`

        cat "/tmp/private_key.pem" | ssh-add -
        echo "ssh_auth_sock=${SSH_AUTH_SOCK}" >> $GITHUB_OUTPUT

    - name: Cache step
      id: cache-step
      uses: actions/cache@v3
      with:
        path: agent_build_output/step_cache/${{ inputs.cache_key }}
        key: ${{ inputs.cache_key }}

    - name: Run cached step
      shell: bash
      env:
        SSH_AUTH_SOCK: ${{ steps.prepare-ssh.outputs.ssh_auth_sock }}
        AWS_ACCESS_KEY: ${{ inputs.aws_access_key }}
        AWS_SECRET_KEY: ${{ inputs.aws_secret_key }}
        AWS_PRIVATE_KEY_NAME: ${{ inputs.aws_private_key_name }}
        AWS_PRIVATE_KEY_PATH: "/tmp/private_key.pem"
        AWS_REGION: ${{ inputs.aws_region }}
        AWS_SECURITY_GROUP: ${{ inputs.aws_security_group }}
        AWS_SECURITY_GROUPS_PREFIX_LIST_ID: ${{ inputs.aws_prefix_list_id }}
        AWS_OBJECTS_NAME_PREFIX: ${{ inputs.aws_objects_name_prefix }}
      run: |
        venv/bin/python3 agent_build_refactored/scripts/runner_helper.py ${{ inputs.step_runner_fqdn }} --run-all-cacheable-steps