name: "Build cacheable dependency"
description: "Run build of one cacheable dependency"

inputs:
  dependency_id:
    description: "Id of the dependency to build"

  python_version:
    description: "Version of Python to use"

runs:
  using: "composite"
  steps:
    - name: install python and requirements
      uses: ./.github/actions/install_python_and_requirements
      with:
        python_version: ${{ inputs.python_version }}

    - name: Expose GitHub Runtime To Be Able to Use GHA Cache By Docker.
      uses: crazy-max/ghaction-github-runtime@715c25b40ccc0df9b62bfa8be3ccc57d09dbc4b1

    - name: Build dependency
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
          USE_GHA_CACHE: "1"
      run: |
        python3 agent_build_refactored/scripts/cicd/run_dependency.py ${{ inputs.dependency_id }}
      
