name: "Build cacheable dependency"
description: "Run build of one cacheable dependency"

inputs:
  dependency_id:
    description: "Id of the dependency to build"

  python_version:
    description: "Version of Python to use"

  cache_version:
    description: Version suffix for the cache key. May be useful when it is needed to invalidate the cache.

runs:
  using: "composite"
  steps:
    - name: install python and requirements
      uses: ./.github/actions/install_python_and_requirements
      with:
        python_version: ${{ inputs.python_version }}

    - name: Expose GitHub Runtime To Be Able to Use GHA Cache By Docker.
      uses: crazy-max/ghaction-github-runtime@715c25b40ccc0df9b62bfa8be3ccc57d09dbc4b1

    - name: Build dependency
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
          USE_GHA_CACHE: "1"
          CACHE_VERSION: ${{ inputs.cache_version }}
          AWS_PRIVATE_KEY_PATH: /tmp/private_key.pem
      run: |
        echo "${AWS_DEV_EC2_PRIVATE_KEY}" > "${AWS_PRIVATE_KEY_PATH}"
        chmod 600 "${AWS_PRIVATE_KEY_PATH}"
        python3 agent_build_refactored/scripts/cicd/run_dependency.py ${{ inputs.dependency_id }}
      
