apiVersion: batch/v1
kind: Job
metadata:
  name: agent-k8s-codespeed
spec:
  template:
    spec:
      shareProcessNamespace: true
      restartPolicy: OnFailure
      containers:
        - name: metric-capture
          image: agent_metrics_capture
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "60Mi"
            requests:
              memory: "60Mi"
          volumeMounts:
            - mountPath: /agent-data
              name: agent-data
            - mountPath: /capture
              name: captured-metrics-backup
          command: ["/bin/sh", "-c"]
          args: ["benchmarks/scripts/start-capture-metrics.sh ${COMMIT_SHA1}; benchmarks/scripts/send-log-level-counts-to-codespeed.sh ${COMMIT_SHA1}"]
          env:
            - name: CAPTURE_TIME
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: capture_time
            - name: CAPTURE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: capture_interval
            - name: CODESPEED_AUTH
              valueFrom:
                secretKeyRef:
                  name: agent-secret
                  key: CODESPEED_AUTH
            - name: CODESPEED_URL
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: codespeed_url
            - name: CODESPEED_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: codespeed_project
            - name: CODESPEED_EXECUTABLE
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: codespeed_executable
            - name: CODESPEED_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: codespeed_environment
            - name: CODESPEED_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: branch
            - name: COMMIT_DATE
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: commit_date
            - name: COMMIT_SHA1
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: commit_sha1
            - name: AGENT_DATA_PATH
              value: /agent-data
        - name: agent
          image: agent-k8s-2.7
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: agent-data
              mountPath: /root/scalyr-agent-dev
          env:
            - name: SCALYR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-secret
                  key: SCALYR_API_KEY
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: server_host
            - name: AGENT_GIT_URL
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: agent_git_url
            - name: COMMIT_SHA1
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: commit_sha1
            - name: SCALYR_SERVER
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: scalyr_server
            - name: BRANCH
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: branch
        - name: log-writer
          image: agent-line-writer
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
          volumeMounts:
            - name: agent-data
              mountPath: /agent-data
          env:
            - name: AGENT_DATA_PATH
              value: /agent-data

      volumes:
        - name: config
          configMap:
            name: codespeed-config
            items:
              - key: agent_no_monitored_logs.json
                path: config.json
        - name: agent-data
          emptyDir: {}
        - name: captured-metrics-backup
          emptyDir: {}



