configMapGenerator:
- name: codespeed-config
  files:
  - agent_config.json
  literals:
    - codespeed_url=https://scalyr-agent-codespeed.herokuapp.com/
    - codespeed_project=scalyr-agent-2
    - codespeed_environment=Kubernetes Medium Size
    - branch=master

    - capture_time=4h
    - capture_interval=60

    - agent_git_url=https://github.com/scalyr/scalyr-agent-2.git
    - scalyr_server=agent.scalyr.com
    - agent_data_path=/root/scalyr-agent-dev
resources:
  - codespeed.yaml