name: Run pre-built jobs.

on:
  workflow_call:
    inputs:
      aws_private_key_name:
        type: string
      aws_region:
        type: string
      aws_security_group:
        type: string
      aws_prefix_list_id:
        type: string
      aws_objects_name_prefix:
        type: string

    secrets:
      CT_AWS_DEV_EC2_PRIVATE_KEY:
        required: true
      CT_AWS_DEV_EC2_ACCESS_KEY:
        required: true
      CT_AWS_DEV_EC2_SECRET_KEY:
        required: true
      CT_SCALYR_TOKEN_PROD_US_CLOUDTECH_TESTING_WRITE:
        required: true
      CT_SCALYR_TOKEN_PROD_US_CLOUDTECH_TESTING_READ:
        required: true

permissions:
  contents: read

jobs:
  run_pre_built_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2.0.0
        with:
          driver-opts: network=host

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: all

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare environment.
        uses: ./.github/actions/execute-runner
        with:
          runner-fqdn: "agent_build_refactored.__init__.BuildTestEnvironment"

      - name: Prepare SSH
        id: prepare-ssh
        shell: bash
        run: |
          echo '${{ secrets.CT_AWS_DEV_EC2_PRIVATE_KEY }}' > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem
          eval `ssh-agent -s`

          cat "/tmp/private_key.pem" | ssh-add -
          echo "ssh_auth_sock=${SSH_AUTH_SOCK}" >> $GITHUB_OUTPUT

      - name: Run cached step
        uses: ./.github/actions/execute-runner
        env:
          SSH_AUTH_SOCK: ${{ steps.prepare-ssh.outputs.ssh_auth_sock }}
        with:
          runner-fqdn: ${{ matrix.step-runner-fqdn }}
          aws_access_key: ${{ secrets.CT_AWS_DEV_EC2_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.CT_AWS_DEV_EC2_SECRET_KEY }}
          aws_private_key_path:  "/tmp/private_key.pem"
          aws_private_key_name: ${{ inputs.aws_private_key_name }}
          aws_region: ${{ inputs.aws_region }}
          aws_security_group: ${{ inputs.aws_security_group }}
          aws_security_groups_prefix_list_id: ${{ inputs.aws_prefix_list_id }}
          aws_objects_name_prefix: ${{ inputs.aws_objects_name_prefix }}
