version: 2.1

commands:
  deployment-step:
    description: "A base command for all tox based unit test jobs"
    parameters:

      step-name:
        description: "Name of the step. Will be also used as cache key."
        type: string

      action:
        description: "Save or restore from cache."
        type: enum
        enum: ["save-cache", "restore-cache", "perform"]

    steps:
      - when:
          condition:
            equal: [ restore, << parameters.action >> ]
          steps:
            - restore_cache:
                key: deployment-steps-cache-<< parameters.step-name >>

      - when:
          condition:
            equal: [ save, << parameters.action >> ]
          steps:
            - save_cache:
                key: deployment-steps-cache-<< parameters.step-name >>
                paths:
                  ~/deployment-steps-cache/<< parameters.step-name >>


  perform-deployment-steps:
    description: "A base command for all tox based unit test jobs"
    parameters:
      step-cache-name:
        description: "Name of the step cache. Will be used as cache key."
        type: string

      action:
        description: "Save or restore from cache."
        type: enum
        enum: [ "save", "restore" ]

    steps:
{{ used_steps }}




jobs:
  unit_test:
    parameters:
      ggg:
        type: string
    docker:
      - image: cimg/python:3.8.10
    steps:
      - checkout
      - run:
          command: |
            echo << parameters.ggg >>

workflows:
  build_and_test:
    jobs:
      - unit_test:
          matrix:
            parameters:
              ggg: ["1", "2"]

  build_and_test2:
    jobs:
      - unit_test:
          matrix:
            parameters:
              ggg: [ "3", "4" ]