version: 2.1

commands:
  deployment-step:
    description: "A base command for all tox based unit test jobs"
    parameters:

      step-name:
        description: "Name of the step. Will be also used as cache key."
        type: string

      action:
        description: "Save or restore from cache."
        type: enum
        enum: ["save-cache", "restore-cache", "perform"]

    steps:
      - run: |
          if [ "$CIRCLE_BRANCH" = "develop" ]; then
              circleci-agent step halt
          fi

      - when:
          condition:
            equal: [ restore, << parameters.action >> ]
          steps:
            - restore_cache:
                key: deployment-steps-cache-<< parameters.step-name >>

      - when:
          condition:
            equal: [ save, << parameters.action >> ]
          steps:
            - save_cache:
                key: deployment-steps-cache-<< parameters.step-name >>
                paths:
                  ~/deployment-steps-cache/<< parameters.step-name >>

{{ deployments_commands }}


orbs:
  win: circleci/windows@2.3.0

executors:
  docker:
    docker:
      - image: cimg/python:3.8.10


jobs:
  unit_test:
    parameters:
      os:
        type: executor
    working_directory: ~/scalyr-agent-2
    executor: << parameters.os >>
    shell: bash
    steps:
      - checkout
      - test_environment_x86_64
      - run:
          name: Run unit tests.
          command: |
            python3 -m pytest tests/unit


workflows:
  build_and_test:
    jobs:
      - unit_test:
          matrix:
            parameters:
              os: [docker, win/default]