version: 2.1

commands:
  install-python:
    description: "Install python"
    parameters:
      version:
        description: "Version of the Python to install"
        type: string
        default: 3.8.10

    steps:
      - restore_cache:
          key: python-install-cache-{{ arch }}-<< parameters.version >>

      - run:
          condition:
            equal: [ windows, << parameters.os >> ]
          steps:
          name: "Install Python"
          command: choco install python --version=<< parameters.version >> --cache ~/python-cache

      - save_cache:
          key: python-install-cache-{{ arch }}-<< parameters.version >>
          paths:
            ~/python-cache

{{ deployments_commands }}


orbs:
  win: circleci/windows@2.3.0

executors:
  docker:
    docker:
      - image: cimg/python:3.8.10

  windows:
    description: Windows executor.
    machine:
      image: 'windows-server-2019-vs2019:stable'
      resource_class: windows.medium
      shell: bash


jobs:
  unit_test:
    parameters:
      os:
        type: executor
    working_directory: ~/scalyr-agent-2
    executor: << parameters.os >>
    steps:
      - checkout
      - install-python
      - << parameters.deployment-name >>
      - run:
          name: Run unit tests.
          command: |
            python3 -m pytest tests/unit


workflows:
  build_and_test:
    jobs:
      - unit_test:
          matrix:
            parameters:
              os: [windows]
              deployment-name: ['test_environment_x86_64']