version: 2.1
orbs:
jobs:
  unit_test:
    parameters:
      ggg:
        type: string
    docker:
      - image: cimg/python:3.8.10
    steps:
      - checkout
      - run:
          command: |
            echo << parameters.ggg >>

workflows:
  build_and_test:
    jobs:
      - unit_test:
          matrix:
            parameters:
              ggg: [1, 2]