name: "Init job matrices"
description: "This action accepts matrices for the jobs that are used in the agent-build workflow and excludes job that are must not be executed in mon-master runs."

inputs:
  images-to-build:
    description: "JSON-formatted job matrix for images to build."
    required: true

  k8s-images-tests:
    description: "JSON-formatted job matrix for Kubernetes image tests."
    required: true

  docker-images-tests:
    description: "JSON-formatted job matrix for docker image tests."
    required: true

outputs:
  to_publish:
    description: "Boolean flag that indicates that result build artifacts has to be published."
    value: ${{ steps.get-job-matrices.outputs.to_publish }}
  pre_build_steps_matrix_json:
    description: "JSON-formatted job matrix for steps that has to be built in separate jobs."
    value: ${{ steps.get-job-matrices.outputs.pre_build_steps_matrix_json }}
  agent_image_build_matrix_json:
    description: "Final JSON-formatted job matrix to build images."
    value: ${{ steps.get-job-matrices.outputs.agent_image_build_matrix_json }}
  k8s_test_matrix_json:
    description: "Final JSON-formatted job matrix for Kubernetes image tests."
    value: ${{ steps.get-job-matrices.outputs.k8s_test_matrix_json }}
  docker_test_matrix_json:
    description: "Final JSON-formatted job matrix for docker image tests."
    value: ${{ steps.get-job-matrices.outputs.docker_test_matrix_json }}


runs:
  using: "composite"
  steps:
    - name: Get job matrices.
      id: get-job-matrices
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}"
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        set -e
        
        cat <<EOT > /tmp/images-build-matrix.json
        ${{ inputs.images-to-build }}
        EOT
        
        cat <<EOT > /tmp/k8s_images-test-matrix.json
        ${{ inputs.k8s-images-tests }}
        EOT
        
        cat <<EOT > /tmp/docker_images-test-matrix.json
        ${{ inputs.docker-images-tests }}
        EOT
        
        python3 agent_build_refactored/scripts/get_github_actions_job_matrices.py \
          --images-build-matrix-json-file /tmp/images-build-matrix.json \
          --k8s-images-test-matrix-json-file /tmp/k8s_images-test-matrix.json \
          --docker-images-test-matrix-json-file /tmp/docker_images-test-matrix.json \
          > /tmp/final_matrices.json
        
        echo "::set-output name=pre_build_steps_matrix_json::$(cat /tmp/final_matrices.json | jq -c '.pre_build_steps_matrix')"
        echo "::set-output name=agent_image_build_matrix_json::$(cat /tmp/final_matrices.json | jq -c '.agent_image_build_matrix')"
        echo "::set-output name=k8s_test_matrix_json::$(cat /tmp/final_matrices.json | jq -c '.k8s_test_matrix_json')"
        echo "::set-output name=docker_test_matrix_json::$(cat /tmp/final_matrices.json | jq -c '.docker_test_matrix_json')"
        echo "::set-output name=to_publish::$(cat /tmp/final_matrices.json | jq -c '.to_publish')"

    - name: Print job matrices
      shell: bash
      run: |

        echo "Image pre-build steps job matrix: "
        echo '${{ steps.get-job-matrices.outputs.pre_build_steps_matrix_json }}' | jq --color-output
        
        echo "Image build job matrix: "
        echo '${{ steps.get-job-matrices.outputs.agent_image_build_matrix_json }}' | jq --color-output
        
        echo "Kubernetes images tests job matrix: "
        echo '${{ steps.get-job-matrices.outputs.k8s_test_matrix_json }}' | jq --color-output
        
        echo "Docker images tests job matrix: "
        echo '${{ steps.get-job-matrices.outputs.docker_test_matrix_json }}' | jq --color-output
        
        echo "Publish artifacts = ${{ steps.get-job-matrices.outputs.to_publish }}"
