name: 'Prepare environment'
description: "Prepares current machine by running one of the 'Deployers', which are defined in the 'agent_build/environment_deployers' folder"
inputs:
  name:
    description: 'Name of the deployer.'
    required: true
  base-docker-image:
    description: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Calculate the checksum of the files used in deployer.
      id: deployer-info
      shell: bash
      run: |
          echo "::set-output name=checksum::$(python3 agent_build/environment_deployers/deployers.py get-info ${{ inputs.name }} checksum)"
          echo "::set-output name=base-deployer-name::$(python3 agent_build/environment_deployers/deployers.py get-info ${{ inputs.name }} base-deployer)"

    - name: Run base deployer if specified.
      if: steps.deployer-info.outputs.base-deployer-name
      uses: ./.github/actions/prepare-environment
      with:
        name: ${{ steps.deployer-info.outputs.base-deployer-name }}
        base-docker-image: ${{ inputs.base-docker-image }}


#    - name: Calculate the checksum of the files used in deployer.
#      shell: bash
#      run: |
#        python3 agent_build/environment_deployers/deployers.py dump-checksum ${{ inputs.name }} > checksum.txt

    - name: Restore cached dependensies of the environment deployer.
      uses: actions/cache@v2
      env:
        cache-version: v8
      with:
        path: ~/dependencies_cache
        key: deployer-${{ inputs.name }}-${{ inputs.base-docker-image }}-${{ runner.os }}-${{ env.cache-version }}-${{ steps.deployer-info.outputs.checksum }}

    - name: Prepare build environment.
      shell: bash
      run: |
        python3 agent_build/environment_deployers/deployers.py deploy ${{ inputs.name }} --base-docker-image  "${{ inputs.base-docker-image }}" --cache-dir ~/dependencies_cache

        # in some cases, the 'deploy' command also generates file 'paths.txt'. This file contains paths
        # to binaries of all tools that are needed for the build. Use this file to add those paths to the PATH env.
        # variable to be able to use those tools.
        if [ -f ~/dependencies_cache/paths.txt ]; then
          cat ~/dependencies_cache/paths.txt >> $GITHUB_PATH
        fi

        ## Remove checksum file, it is not needed anymore.
        #rm checksum.txt