apiVersion: v1
kind: ConfigMap
data:
  SCALYR_K8S_CLUSTER_NAME: kubecon-2023-demo
  SCALYR_SERVER: "https://upload.eu.scalyr.com"
  SCALYR_K8S_EVENTS_DISABLE: "false"
  SCALYR_K8S_IGNORE_NAMESPACES: ""
metadata:
  name: scalyr-config
  namespace: scalyr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scalyr-config-agent-d
  namespace: scalyr
data:
  global-disable-k8s-cert-validation.json: |
    {
      "k8s_verify_api_queries": false,
      "k8s_verify_kubelet_queries": false,
    }
  docker.json: |
    {
      "monitors": [
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_monitor",
        }
      ]
    }
  k8s-events.json: |
    {
      "monitors": [
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_events_monitor",
          //"ignore_master": false,
        }
      ]
    }
  k8s-openmetrics-monitor.json: |
    {
        "monitors":
        [
            {
              module:  "scalyr_agent.builtin_monitors.kubernetes_openmetrics_monitor",
              include_node_name: true,
              include_cluster_name: true,
              logger_include_node_name: false,
              verify_https: false,
              scrape_kubernetes_api_metrics: true,
              kubernetes_api_metrics_scrape_interval: 60,
              scrape_kubernetes_api_cadvisor_metrics: true,
              kubernetes_api_cadvisor_metrics_scrape_interval: 60,
              sample_interval: 60,
              scrape_interval: 60
          }
      ]
    }
