# The main "setup" workflow, that calls other workflows.
name: Docker Images Build

on: [push]

permissions:
  contents: read

# Agent Docker image tests
#
# To test this workflow with your branch, make the following changes:
#
# 1. In this workflow, change ``@master`` to ``@your_branch_name`` - e.g. ``@docker_image_alpine``

# 2. In this workflow, change docker hub secrets to utilize testing and not prod account so images
#    get pushed to testing account. Change ``_PROD_` in the secret name to ``_TEST``,
#    e.g. ``DOCKER_HUB_USERNAME_TEST_ACCOUNT`` ``DOCKER_HUB_PASSWORD_TEST_ACCOUNT``.
#    Images for test account will get pushed to https://hub.docker.com/r/test4scalyr/.
#
# 3. In the job 'publish-images' below, change 'refs/heads/improve-caching-test' in the job conditional to you current branch.:
#
# For example: https://github.com/scalyr/scalyr-agent-2/pull/804/commits/0eccf278623552b51d9289d75a47794e88f02862
jobs:
  pre-job:
    runs-on: ubuntu-20.04
    outputs:
      pre-built-cached-steps-matrix: ${{ steps.get-job-matrices.outputs.pre-built-cached-steps-matrix }}
      build-matrix-json: ${{ steps.get-job-matrices.outputs.build-matrix-json }}
      test-matrix-json: ${{ steps.get-job-matrices.outputs.test-matrix-json }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.13"

      - name: Perform the deployment of the test environment
        uses: ./.github/actions/perform-deployment
        with:
          deployment-name: "agent_build.__init__.BuildTestEnvironment"

      - name: "Get build and test job matrices."
        id: get-job-matrices
        run: |
          set -e 
          echo "Build job matrix:"
          echo "$(python3 -m agent_build.package_builders)"
          echo "Test job matrix: "
          echo "$(python3 -m tests.end_to_end_tests.container_image_tests.k8s_test)"
          echo "::set-output name=build-matrix-json::$(python3 -m agent_build.package_builders)"
          echo "::set-output name=test-matrix-json::$(python3 -m tests.end_to_end_tests.container_image_tests.k8s_test)"
          
          echo "::set-output name=pre-built-cached-steps-matrix::$(python3 -m agent_build.scripts.prebuild_steps_on_cicd)"

  pre-build-cached-step:
    needs:
      - pre-job

    runs-on: ${{ matrix.os }}
    strategy:
      # This job receives its matrix from the previous job. The matrix itself is created by the agent_build/scripts/prebuild_steps_on_cicd.py  module.
      # The matrix, for now, consists only from the 'include' part with following fields:
      #   "step-builder-fdqn": Fully qualified name of the builder class that has to run the cached step.
      #   "python-version": Version of python to setup on this runner. (NOTE: version of python used in images may differ, and it specified in the source code.)
      #   "os": Runner OS.
      matrix: ${{ fromJSON(needs.pre-job.outputs.pre-built-cached-steps-matrix) }}

    env:
      DOCKER_BUILDKIT: 1
      # Set this variable to tell the agent build code that it runs in CI/CD and it needs to use caching.
      AGENT_BUILD_IN_CICD: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # v2.0.0
        with:
          driver-opts: network=host

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # v2
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: all

      - name: Run cached step.
        uses: ./.github/actions/perform-deployment
        with:
          deployment-name: ${{ matrix.step-builder-fqdn }}

  build-images:
    needs:
      - pre-job
      - pre-build-cached-step
    runs-on: ${{ matrix.os }}

    strategy:
      # This job receives its matrix from the previous job. The matrix itself is created by the agent_build/package_builder.py module.
      # The matrix, for now, consists only from the 'include' part with following fields:
      #   "builder-name": name of the builder that builds the target image.
      #   "result-tarball-name": filename of the result image tarball.
      #   "python-version": Version of python to setup on this runner. (NOTE: version of python used in images may differ, and it specified in the source code.)
      #   "os": Runner OS.
      matrix: ${{ fromJSON(needs.pre-job.outputs.build-matrix-json) }}

    env:
      DOCKER_BUILDKIT: 1
      # Set this variable to tell the agent build code that it runs in CI/CD and it needs to use caching.
      AGENT_BUILD_IN_CICD: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

#      - name: Perform the deployment of the test environment
#        uses: ./.github/actions/perform-deployment
#        with:
#          deployment-name: "agent_build.__init__.BuildTestEnvironment"

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # v2
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # v2.0.0
        with:
          driver-opts: network=host

      - name: Get builder fqdn
        id: get-builder-fqdn
        run: |
          set -e
          echo "::set-output name=fqdn::$(python3 build_package_new.py ${{ matrix.builder-name }} --fqdn)"

      - name: Perform the build of the base docker image in the deployment.
        uses: ./.github/actions/perform-deployment
        with:
          deployment-name: ${{ steps.get-builder-fqdn.outputs.fqdn }}


      # We build all images with tha same base image all at once and store all result images in a single
      # registry.
      - name: Build images with builder '${{ matrix.builder-name }}'
        run: |
          python3 build_package_new.py ${{ matrix.builder-name }} \
            --image-output-path /tmp/build-output

      - name: Save result image tarball.
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.builder-name }}
          path: /tmp/build-output/${{ matrix.result-tarball-name }}


  test-k8s-images:
    needs:
      - build-images
      - pre-job
      - pre-build-cached-step
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      # This job receives its matrix from the preparation job. The matrix itself is created by the tests/end_to_end_tests/container_image_tests/k8s_test.py module.
      # The matrix, for now, consists only from the 'include' part with following fields:
      #   "pytest-params": String with all parameters for a particular test variant which then goes to "parametrize" test cases which has to be run there.
      #   "builder-name": name of the builder that builds the target image.
      #   "result-tarball-name": filename of the result image tarball.
      #   "os": Runner's OS
      #   "python-version": Version of the python installed on runner.
      matrix: ${{ fromJSON(needs.pre-job.outputs.test-matrix-json) }}

    env:
      DOCKER_BUILDKIT: 1
      # Set this variable to tell the agent build code that it runs in CI/CD and it needs to use caching.
      AGENT_BUILD_IN_CICD: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Perform the deployment of the test environment
        uses: ./.github/actions/perform-deployment
        with:
          deployment-name: "agent_build.__init__.BuildTestEnvironment"

      - name: Download registry with previously built images.
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.builder-name }}
          path: /tmp/build-output/${{ matrix.result-tarball-name }}

      - name: Run tests
        shell: bash
        run: |
          python3 -m pytest  tests/end_to_end_tests/container_image_tests/k8s_test.py \
              -k ${{ matrix.pytest-params }} \
            --image-tarball-path /tmp/build-output/${{ matrix.result-tarball-name }} \
            --scalyr-api-key ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }} \
            --scalyr-api-read-key ${{ secrets.SCALYR_CLOUDTECH_TESTING_DEV_SCALYR_READ_API_KEY }} \
            --test-session-suffix ${{ github.run_id }}-${{ github.run_attempt }}

      - name: Notify Slack on Failure
        # NOTE: github.ref is set to pr ref (and not branch name, e.g. refs/pull/28/merge) for pull
        # requests and that's why we need this special conditional and check for github.head_ref in
        # case of PRs
        if: ${{ failure() && (github.ref == 'refs/heads/master' || github.head_ref == 'master') }}
        uses: act10ns/slack@87c73aef9f8838eb6feae81589a6b1487a4a9e08 # v1.6.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#cloud-tech'
#
#  publish-images:
#    if: ${{ github.ref == 'refs/heads/master' || github.ref_type == 'tag' }}
#    needs:
#      - test-images
#
#    uses: scalyr/scalyr-agent-2/.github/workflows/publish-docker-images.yml@master
#    secrets:
#      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
#      SCALYR_CLOUDTECH_TESTING_DEV_SCALYR_READ_API_KEY: ${{ secrets.SCALYR_CLOUDTECH_TESTING_DEV_SCALYR_READ_API_KEY }}
#      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME_PROD_ACCOUNT }}
#      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD_PROD_ACCOUNT }}
