name: Build agent packages.

on: [push]

env:
  DOCKER_BUILDKIT: 1


jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: set-matrix
        run: echo "::set-output name=matrix::{\"project\":\"foo\",\"config\":\"Debug\"}"


      - run: echo "${{steps.outputs.set-matrix.outputs.matrix}}"


      - name: Prepare build environment by running appropriate deployer.
        id: prepare
        uses: ./.github/actions/run-environment-deployer
        with: ${{fromJson(steps.outputs.set-matrix.outputs.matrix)}}



  deb_x86_64:
    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
    with:
      package_name: deb_x86_64
    secrets:
      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}

#  deb_arm64:
#    name: deb_arm64
#    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
#    with:
#      package_name: deb_arm64
#      os: ubuntu-20.04
#    secrets:
#      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}

  rpm_x86_64:
    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
    with:
      package_name: rpm_x86_64
    secrets:
      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}


  tar_x86_64:
    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
    with:
      package_name: tar_x86_64
    secrets:
      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}

  msi_x86_64:
    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
    with:
      package_name: msi_x86_64
      os: windows-2019
    secrets:
      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}