# The main "setup" workflow, that calls other workflows.
name: Docker Images Build

on: [push]

env:
  # Set this variable to tell the agent build code that it runs in CI/CD and it needs to use caching.
  IN_CICD: "1"

# Agent Docker image tests
jobs:
  build-docker-images:
    uses: scalyr/scalyr-agent-2/.github/workflows/docker-and-k8s.yml@master
    secrets:
      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
      SCALYR_CLOUDTECH_TESTING_DEV_SCALYR_READ_API_KEY: ${{ secrets.SCALYR_CLOUDTECH_TESTING_DEV_SCALYR_READ_API_KEY }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME_TEST_ACCOUNT }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD_TEST_ACCOUNT }}