name: Build agent packages.

on: [push]

env:
  DOCKER_BUILDKIT: 1


jobs:
#  deb_x86_64:
#    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
#    with:
#      package_name: deb_x86_64
#    secrets:
#      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
#      SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_KEY: ${{ secrets.SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_KEY }}
#      SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_SECRET: ${{ secrets.SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_SECRET }}
#      AWS_DEV_US_EAST_1_KEYPAIR_NAME: ${{ secrets.AWS_DEV_US_EAST_1_KEYPAIR_NAME }}
#

#  deb_arm64:
#    name: deb_arm64
#    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
#    with:
#      package_name: deb_arm64
#      os: ubuntu-20.04
#    secrets:
#      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}

#  rpm_x86_64:
#    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
#    with:
#      package_name: rpm_x86_64
#    secrets:
#      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
#
#
#  tar_x86_64:
#    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
#    with:
#      package_name: tar_x86_64
#    secrets:
#      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}

#  msi_x86_64:
#    uses: scalyr/scalyr-agent-2/.github/workflows/build-and-test-agent-package.yml@refactor-tests
#    with:
#      package_name: msi_x86_64
#      os: windows-2019
#    secrets:
#      SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
#      SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_KEY: ${{ secrets.SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_KEY }}
#      SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_SECRET: ${{ secrets.SCALYR_CLOUDTECH_TESTING_DEV_AWS_ACCESS_SECRET }}
#      AWS_DEV_US_EAST_1_KEYPAIR_NAME: ${{ secrets.AWS_DEV_US_EAST_1_KEYPAIR_NAME }}