name: "Docker and K8s"

on: push



jobs:

  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000


#    strategy:
#      matrix:
#        platforms: [ linux/amd64, linux/arm64 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: localhost:5000/scalyr/scalyr-agent-2:latest

    - name: Inspect
      run: |
        docker buildx imagetools inspect localhost:5000/scalyr/scalyr-agent-2:latest


    - name: Test
      env:
        SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
      run: |
        docker pull localhost:5000/scalyr/scalyr-agent-2:latest
        docker run -d --name scalyr-docker-agent \
        -e SCALYR_API_KEY=$SCALYR_API_KEY \
        -v /var/run/docker.sock:/var/scalyr/docker.sock \
        -v /var/lib/docker/containers:/var/lib/docker/containers \
        localhost:5000/scalyr/scalyr-agent-2:latest

        sleep 10

        docker logs scalyr-docker-agent

        docker kill -f scalyr-docker-agent






#
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        platforms: [linux/amd64, linux/arm64]
#
#    st