name: Build agent packages.

on: [push]

env:
  DOCKER_BUILDKIT: 1


jobs:
  # TODO move here tests from the CicleCi.
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build-type: docker-json
            # Rename that to the real name after test with dockerhub credentials.
            image-name: scalyr/scalyr-agent-release-test-image
          - build-type: docker-syslog
            # Rename that to the real name after test with dockerhub credentials.
            image-name: scalyr/scalyr-agent-release-test-image
          - build-type: k8s
            # Rename that to the real name after test with dockerhub credentials.
            image-name: scalyr/scalyr-agent-release-test-image


    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push image to the local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.unified
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            localhost:5000/${{ matrix.image-name }}
          build-args: |
            BUILD_TYPE=${{ matrix.build-type }}

      - name: Build and push image from master branch.
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: .
          file: docker/Dockerfile.unified
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ matrix.image-name }}:${{ github.sha }}
          build-args: |
            BUILD_TYPE=${{ matrix.build-type }}


      - name: Build and push image from tag.
        uses: docker/build-push-action@v2
        if: ${{ github.ref_type == 'tag' }}
        with:
          context: .
          file: docker/Dockerfile.unified
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ matrix.image-name }}:${{ github.github.ref_name }}
          build-args: |
            BUILD_TYPE=${{ matrix.build-type }}



