name: Packages build

on: [push]

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python: ["3.8"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install python.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'

      - name: Prepare environment for the tests.
        id: prepare
        uses: ./.github/actions/prepare-environment
        with:
          name: 'test'

      - name: Run unit tests.
        shell: bash
        run: |
          python -m pytest ./tests/unit

