name: Packages build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - package_type: "deb"
            package_name: "scalyr-agent-2_*.*.*_all.deb"
            os: ubuntu-20.04
            python-version: "3.8"
          - package_type: "rpm"
            package_name: "scalyr-agent-2-*.*.*-*.noarch.rpm"
            os: ubuntu-20.04
            python-version: "3.8"
          - package_type: "tar"
            package_name: "scalyr-agent-*.*.*.tar.gz"
            os: ubuntu-20.04
            python-version: "3.8"
          - package_type: "msi"
            package_name: "ScalyrAgentInstaller-*.*.*.msi"
            os: windows-2019
            python-version: "3.8"
          - package_type: "k8s"
            os: ubuntu-20.04
            package_name: "scalyr-agent-k8s-*.*.*"
            python-version: "3.8"
          - package_type: "docker-json"
            os: ubuntu-20.04
            package_name: "scalyr-agent-docker-json-*.*.*"
            python-version: "3.8"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate the checksum of the build dependencies.
        shell: bash
        run: |
          python3 agent_build/build_package.py ${{ matrix.package_type }} dump-checksum checksum.txt

      - name: Restore cached dependensies of the build environment if exists.
        uses: actions/cache@v2
        env:
          cache-version: v1
        with:
          path: ~/dependencies_cache
          key: ${{ runner.os }}-build-dependencies-${{ env.cache-version }}-${{ hashFiles('checksum.txt') }}

      - name: Prepare build environment.
        shell: bash
        run: |
          python3 agent_build/build_package.py ${{ matrix.package_type }} prepare-build-environment --cache-dir ~/dependencies_cache

          # in some cases, the 'prepare-build-environment' command also generates file 'paths.txt'. This file contains paths
          # to binaries of all tools that are needed for the build. Use this file to add those paths to the PATH env.
          # variable to be able to use those tools.
          if [ -f ~/dependencies_cache/paths.txt ]; then
            cat ~/dependencies_cache/paths.txt
            cat ~/dependencies_cache/paths.txt >> $GITHUB_PATH
          fi

          # Remove checksum file, it is not needed anymore.
          rm checksum.txt



      - name: Build.
        shell: bash
        run: |
          python agent_build/build_package.py ${{ matrix.package_type }} build --output-dir agent-build-output


      - name: Save the package.
        uses: actions/upload-artifact@v2
        if: ${{ ! matrix.package_name }}
        with:
          name: "package-${{ matrix.package_type }}"
          path: |
            agent-build-output/*.${{ matrix.package_type }}*

      - name: Save the package.
        uses: actions/upload-artifact@v2
        if: ${{ matrix.package_name }}
        with:
          name: "package-${{ matrix.package_type }}"
          path: |
            agent-build-output/${{ matrix.package_name }}*



      - name: Save the frozen test script.
        uses: actions/upload-artifact@v2
        with:
          name: "package-test-${{ matrix.package_type }}"
          path: |
            agent-build-output/package_test_frozen_binary/package_test*




  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        package_type: ["deb"]
        os: ["ubuntu-20.04"]
        docker-image: ["ubuntu:14.04", "ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04"]
        python-version: [3.8]
        include:
          - package_type: "rpm"
            os: ubuntu-20.04
            docker-image: "centos:7"
            python-version: "3.8"
          - package_type: "rpm"
            os: ubuntu-20.04
            docker-image: "centos:8"
            python-version: "3.8"
          - package_type: "rpm"
            os: ubuntu-20.04
            docker-image: "amazonlinux:2"
            python-version: "3.8"
          - package_type: "tar"
            os: ubuntu-20.04
            docker-image: "ubuntu:14.04"
            python-version: "3.8"
          - package_type: "msi"
            os: windows-2019
            python-version: "3.8"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: "package-${{ matrix.package_type }}"
          path: ~/package

      - uses: actions/download-artifact@v2
        with:
          name: "package-test-${{ matrix.package_type }}"
          path: ~/package_test

      - name: Test.
        shell: bash
        env:
          SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
        run: |
          ls -al ~/package_test
          chmod +x ~/package_test/package_test*
          ls ~/package/*.${{ matrix.package_type }}*
          python3 tests/package_tests/package_test_runner.py \
            --docker-image "${{ matrix.docker-image }}" \
            --package-path ~/package/*.${{ matrix.package_type }}* \
            --package-test-path ~/package_test/package_test* \
            --scalyr-api-key "$SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN"

  test-k8s:
    needs: build
    runs-on: "ubuntu-20.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: "package-k8s"
          path: ~/package

      - name: Test.
        shell: bash
        env:
          SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
        run: |
          minikube start
          chmod +x ~/package/scalyr-agent-k8s-*.*.*
          python3 tests/package_tests/k8s_test.py \
            --builder-path ~/package/scalyr-agent-k8s-*.*.* \
            --scalyr-api-key "$SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN"

  test-docker:
    needs: build
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        docker-build-type: ["docker-json"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: "package-${{ matrix.docker-build-type }}"
          path: ~/package

      - name: Test.
        shell: bash
        env:
          SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
        run: |
          chmod +x ~/package/scalyr-agent-${{ matrix.docker-build-type }}-*.*.*
          python3 tests/package_tests/docker_test.py \
            --builder-path ~/package/scalyr-agent-${{ matrix.docker-build-type }}-*.*.* \
            --scalyr-api-key "$SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN"





