name: Build all cacheable dependencies

on:
  workflow_call:
    inputs:
      python_version:
        description: "Version of Python to use."
        type: string
#    secrets:
#      CT_AWS_DEV_EC2_PRIVATE_KEY:
#        required: true
#      CT_AWS_DEV_EC2_ACCESS_KEY:
#        required: true
#      CT_AWS_DEV_EC2_SECRET_KEY:
#        required: true
#      CT_SCALYR_TOKEN_PROD_US_CLOUDTECH_TESTING_WRITE:
#        required: true
#      CT_SCALYR_TOKEN_PROD_US_CLOUDTECH_TESTING_READ:
#        required: true

env:
  DOCKER_BUILDKIT: 1


jobs:
  prepare_before_build:
    name: Prepare before dependencies build
    runs-on: ubuntu-latest
    outputs:
      DEPENDENCY_GROUP_MATRIX_0: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_0 }}
      DEPENDENCY_GROUP_MATRIX_1: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_1 }}
      DEPENDENCY_GROUP_MATRIX_2: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_2 }}
      DEPENDENCY_GROUP_MATRIX_3: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_3 }}
      DEPENDENCY_GROUP_MATRIX_4: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_4 }}
      DEPENDENCY_GROUP_MATRIX_5: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_5 }}
      DEPENDENCY_GROUP_MATRIX_6: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_6 }}
      DEPENDENCY_GROUP_MATRIX_7: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_7 }}
      DEPENDENCY_GROUP_MATRIX_8: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_8 }}
      DEPENDENCY_GROUP_MATRIX_9: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_9 }}
      DEPENDENCY_GROUP_MATRIX_10: ${{ steps.get_dependency_matrices.outputs.DEPENDENCY_GROUP_MATRIX_10 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install python and requirements
        uses: ./.github/actions/install_python_and_requirements
        with:
          python_version: ${{ inputs.python_version }}

      - name: Get dependency matrices
        id: get_dependency_matrices
        run: |
          echo "::notice::Can not build all artifacts from cache. Need to build dependencies in order to cache them first."
          MATRICES=$(python3 agent_build_refactored/scripts/cicd/create_cacheable_steps_matrix.py)
          echo "Matrices:"
          echo "${MATRICES}"
          echo "${MATRICES}" >> "${GITHUB_OUTPUT}"

  group_0:
    runs-on: ubuntu-latest
    needs: [prepare_before_build]
    strategy:
      matrix: ${{ fromJSON( needs.prepare_before_build.outputs.DEPENDENCY_GROUP_MATRIX_0) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build dependency
        uses: ./.github/actions/build_cacheable_dependency
        with:
          dependency_id: ${{ matrix.id }}
          python_version: ${{ inputs.python_version }}

  group_1:
    runs-on: ubuntu-latest
    needs: [ prepare_before_build, group_0]
    strategy:
      matrix: ${{ fromJSON( needs.prepare_before_build.outputs.DEPENDENCY_GROUP_MATRIX_1) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build dependency
        uses: ./.github/actions/build_cacheable_dependency
        with:
          dependency_id: ${{ matrix.id }}
          python_version: ${{ inputs.python_version }}

  group_2:
    runs-on: ubuntu-latest
    needs: [ prepare_before_build, group_1]
    strategy:
      matrix: ${{ fromJSON( needs.prepare_before_build.outputs.DEPENDENCY_GROUP_MATRIX_2) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build dependency
        uses: ./.github/actions/build_cacheable_dependency
        with:
          dependency_id: ${{ matrix.id }}
          python_version: ${{ inputs.python_version }}

  group_3:
    runs-on: ubuntu-latest
    needs: [ prepare_before_build, group_2]
    strategy:
      matrix: ${{ fromJSON( needs.prepare_before_build.outputs.DEPENDENCY_GROUP_MATRIX_3) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build dependency
        uses: ./.github/actions/build_cacheable_dependency
        with:
          dependency_id: ${{ matrix.id }}
          python_version: ${{ inputs.python_version }}


